### ISSUE TITLE
Implementation of GitHub actions workflow for continuous integration

### ISSUE THREAD

**Issue by deepaksidhu** [UBC-MDS/RSimplerEDA#26]
Make sure to add this two files into the workflows folder in the repo

- https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml
-  https://github.com/r-lib/actions/blob/master/.github/workflows/test-coverage.yaml

Finally, make sure that the project successfully runs these workflows

**Comment by ChuckHo777** [comment]
The GitHub workflow works!
