### ISSUE TITLE
Discussion about the License used for the RSimplerEDA package

### ISSUE THREAD

**Issue by deepaksidhu** [UBC-MDS/RSimplerEDA#28]
Discussion about the reason for choosing a specific License for the package.

**Comment by deepaksidhu** [comment]
Based on scanning through the different licenses option for our EDA package, 
I highly suggest that we stick with the MIT License for the following reasons.

- It provides permissions for commercial use
- It can be used for distribution, as long as license and copyright notice is included in the distributed work
- It allows anyone who want to continue our work to modify it under the original license specified
- We also allow others to build on our work and use it for their own benefit
- Allows private use

Another aspect that is crucial is that it protects us from liability, If in the future that works from other contributes causes any significant issues.

Let me know if you agree with the choice MIT License for our package. 

Thank you,
Deepak

**Comment by ChuckHo777** [comment]
Do we need to follow the license for  ggplot or altair package as our package built up based on them?

**Comment by nichowu** [comment]
Since the main packages we built upon are ggplot2 and altair, I think we should also use the license they used to keep things consistent. 

It looks like ggplot2 is using MIT license, and altair used a version that builds on MIT license. So I also recommend to use MIT license for our package.

**Comment by deepaksidhu** [comment]
I agree with choice of MIT License for our EDA package for both python and R.

What are your thoughts @ChuckHo777 ?

**Comment by ChuckHo777** [comment]
Great. Let's stick with MIT License.

**Comment by ChuckHo777** [comment]
Done!
